import BurgerIcon from "./assets/images/burger.png";

export default itemsList = [
  {
    id: 1,
    name: "Good Burger",
    image: BurgerIcon,
    cost: "4,5",
    description: "Realno good burger utolit golod u vas i druzey",
    countInCart: 0,
    rate: "4,9",
    likes: "12k+",
  },
  {
    id: 1,
    name: "Good Burger",
    image: BurgerIcon,
    cost: "4,5",
    description: "Realno good burger utolit golod u vas i druzey",
    countInCart: 0,
    rate: "4,9",
    likes: "12k+",
  },
  {
    id: 1,
    name: "Good Burger",
    image: BurgerIcon,
    cost: "4,5",
    description: "Realno good burger utolit golod u vas i druzey",
    countInCart: 0,
    rate: "4,9",
    likes: "12k+",
  },
  {
    id: 1,
    name: "Good Burger",
    image: BurgerIcon,
    cost: "4,5",
    description: "Realno good burger utolit golod u vas i druzey",
    countInCart: 0,
    rate: "4,9",
    likes: "12k+",
  },
  {
    id: 1,
    name: "Good Burger",
    image: BurgerIcon,
    cost: "4,5",
    description: "Realno good burger utolit golod u vas i druzey",
    countInCart: 0,
    rate: "4,9",
    likes: "12k+",
  },
];
